config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get '', to: 'categories#index', as: '/'
    resources :dashboard
    resources :categories 
    resources :pages
    resources :userlogs do
      collection do
        get :mostactivepage
        get :mostactiveuser
        get :userpagecount
        get :userlist
      end
    end
  end

  devise_for :users, controllers: { invitations: 'devise/invitations' },:skip => [:registrations] 

  resources :dashboard
  resources :pages
  resources :userlogs
  root 'dashboard#home'
  get 'home' => 'dashboard#home'
  get 'about' => 'dashboard#about'
  get 'contact' => 'dashboard#contact'
  get 'users/sign_up' => 'dashboard#signup'
  post '/ajax/sum3' => 'pages#ajax_sum3'
   
  
 

end

app/views/admin/pages/edit.html.erb

<div class="container">
<div class="page-header">
<h1>Edit Page</h1> 
</div>


 <%= form_for([:admin, @page]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>

    	<tr>
		     <td> <%= c.label :categorie_id %></td>
		     <td>
		        <%= collection_select(:page, :categorie_id, Categorie.all, :id, :name, { :prompt => false }) %>
		     </td>
		</tr>

		<tr>
		     <td> <%= c.label :title %></td>
		     <td> <%= c.text_field :title %>  </td>
		</tr>
		
		<tr>
		     <td> <%= c.label :content %></td>
		     <td> <%= c.cktext_area :content, rows: 10 %></td>
		</tr>

	    <tr>
	     	<td colspan="2"> 
			<%= link_to 'Cancel', admin_pages_path, class: "btn btn-info category-bttn" %>
			<%= c.submit "Edit Page", class: "btn btn-large btn-primary category-bttn" %>
			</td>
	    </tr>
    
</table>  

<% end %>

<%= tinymce %>
</div>



app/views/admin/pages/index.html.erb
<div class="container">
<div class="page-header">
<h1 class="category">Page List</h1>
<%= link_to 'Dashboard(Home)', admin_path, class: "btn btn-info category-bttn" %>
<%= link_to 'Add New page', new_admin_page_path, class: "btn btn-info category-bttn" %>&nbsp;&nbsp;
</div>



<% if @page.count == 0 %>
<%= "No record presents" %>
<% else %>

<div class="table-responsive">
<table class="table">
<thead>

<tr class="active">
<th >Title</th>
<th>Category</th>
<th>Last Updated</th>
<th></th>
<th></th>
</tr>

<% @page.each do |page| %>
<tr>
<td><%= link_to page.title , [:admin, page] %></td>
<td><%= page.categorie.name.html_safe %></td>
<td><%= page.updated_at.strftime("%d %b, %I:%M%p") %></td>
<td><%= link_to "Edit", edit_admin_page_path(page), class: "btn btn-warning" %></td>
<td><%= link_to "Delete", [:admin, page], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>	
</tr>
<% end %>

</thead>
</table>
</div>

<% end %>	
<br><br>
<%= will_paginate @page %>	
</div>
  

app/views/admin/pages/new.html.erb
<div class="container">
<div class="page-header">
<h1>Add New Page</h1> 
</div>

 <%= form_for([:admin, @page]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>

    	<tr>
		     <td> <%= c.label :categorie_id %></td>
		     <td>
		        <%= collection_select(:page, :categorie_id, Categorie.all, :id, :name, { :prompt => false }) %>
		     </td>
		</tr>

		<tr>
		     <td> <%= c.label :title %></td>
		     <td> <%= c.text_field :title %>  </td>
		</tr>
		
		<tr>
		     <td> <%= c.label :content %></td>
		     <td> <%= c.cktext_area :content, rows: 10 %></td>
		</tr>
		
	    <tr>
	     	<td colspan="2"> 
			<%= link_to 'Cancel', admin_pages_path, class: "btn btn-info category-bttn" %>
			<%= c.submit "Create new Page", class: "btn btn-large btn-primary category-bttn" %>
			</td>
	    </tr>
    
</table>  

<% end %>

<%#= tinymce %>
</div>

app/views/admin/pages/show.html.erb
<%= link_to "Pages", admin_pages_path, class:"btn btn-info back-bttn" %> 
<h1><%= @page.title %> </h1>

<%= @page.content.html_safe %>