config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get '', to: 'categories#index', as: '/'
    resources :dashboard
    resources :categories 
    resources :pages
    resources :userlogs do
      collection do
        get :mostactivepage
        get :mostactiveuser
        get :userpagecount
        get :userlist
      end
    end
  end

  devise_for :users, controllers: { invitations: 'devise/invitations' },:skip => [:registrations] 

  resources :dashboard
  resources :pages
  resources :userlogs
  root 'dashboard#home'
  get 'home' => 'dashboard#home'
  get 'about' => 'dashboard#about'
  get 'contact' => 'dashboard#contact'
  get 'users/sign_up' => 'dashboard#signup'
  post '/ajax/sum3' => 'pages#ajax_sum3'
   
  
 

end

app/views/layouts/headers/_admin_header.html.erb
<!--http://richonrails.com/articles/basic-ajax-in-ruby-on-rails   
http://teapoci.blogspot.in/2008/04/html-editor-or-rich-text-editor-for.html 
http://rushabhhathi.com/2011/08/13/add-rich-text-editor-in-a-rails-app/
-->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<!--<div class="navbar-header">
<div class="navbar-brand">Administration </div>
</div>-->
<div class="navbar-collapse collapse">
<ul class="nav navbar-nav">
<li><%= link_to 'Categories' , admin_categories_path  %></li>
<li><%= link_to 'Pages' , admin_pages_path  %></li>

<li class="dropdown">
<a data-toggle="dropdown" class="dropdown-toggle" href="#">Invitation<span class="caret"></span></a>
<ul role="menu" class="dropdown-menu">
<li><%= link_to "List of invitations Sent",userlist_admin_userlogs_path %></li>
<li><%= link_to "send invitation",new_user_invitation_path %></li>
</ul>
</li>
			
			
			
			
<li class="dropdown">
<a data-toggle="dropdown" class="dropdown-toggle" href="#">Reports<span class="caret"></span></a>
<ul role="menu" class="dropdown-menu">
<li><%= link_to "Check User Log",admin_userlogs_path %></li>
<li><%= link_to "Check User Page Count",userpagecount_admin_userlogs_path %></li>
<li><%= link_to "Most Active User",mostactiveuser_admin_userlogs_path %></li>
<li><%= link_to "Most Active Page", mostactivepage_admin_userlogs_path  %></li>
</ul>
</li>
<li ><%= link_to 'Sign out' , destroy_user_session_path , method: :delete %></li>
</ul>
<div class="welcome">welcome    <%=  current_user.username %></div>
</div>
</div>
</div>


app/views/layouts/headers/_default_header.html.erb
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CaptiveOne Library</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li ><%= link_to "Home", home_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
          </ul>
          
           
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/headers/_referral_source_header.html.erb
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CaptiveOne Library</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          	<li ><%= link_to "Home", home_path %></li>
            <li ><%= link_to "Learn", pages_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path , method: :delete %></li>
			
          </ul>
			
            <%= form_tag(pages_path, :method => "get",  id: "search-form",:class => 'navbar-form navbar-right')  do %>
				
			 	 <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search.." %>
			    
			<% end %>
            <div class="welcome">Welcome    <%=  current_user.username %></div>
        </div><!--/.nav-collapse -->
      </div>
	  
    </div>


app/views/layouts/headers/_sales_manager_header.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'COCRM', "#", class:"navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to current_user.first_name, "#" %></li>
        <li><%= link_to 'Clients', sales_manager_clients_path %></li>
        <li><%= link_to 'Meetings', sales_manager_meetings_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>