config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get '', to: 'categories#index', as: '/'
    resources :dashboard
    resources :categories 
    resources :pages
    resources :userlogs do
      collection do
        get :mostactivepage
        get :mostactiveuser
        get :userpagecount
        get :userlist
      end
    end
  end

  devise_for :users, controllers: { invitations: 'devise/invitations' },:skip => [:registrations] 

  resources :dashboard
  resources :pages
  resources :userlogs
  root 'dashboard#home'
  get 'home' => 'dashboard#home'
  get 'about' => 'dashboard#about'
  get 'contact' => 'dashboard#contact'
  get 'users/sign_up' => 'dashboard#signup'
  post '/ajax/sum3' => 'pages#ajax_sum3'
   
  
 

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!,:is_admin?
  
  def is_admin?
    unless current_user.role.name == "admin"
      flash[:notice] = "You are not authorized to view that."
      self.route_to_proper_controller
    end
  end

  def index
  	@allcategory = Categorie.all.paginate(page: params[:page], per_page: 2)
    #@allcategory = Categorie.paginate(:all, :order => "name ASC", :per_page => 2, :page => params[:page])
  end

  def show
  	@category = Categorie.find(params[:id])
  end

  def new
    @category = Categorie.new
  end
  
  def create
    @allcategory = Categorie.all.paginate(page: params[:page], per_page: 2)
    @category = Categorie.create(cat_params)
  end

  def edit
    @category = Categorie.find(params[:id])
  end


  def update
    @allcategory = Categorie.all.paginate(page: params[:page], per_page: 2)
    @category = Categorie.find(params[:id])
    @category.update_attributes(cat_params)
  end

  def destroy
    Categorie.find(params[:id]).destroy
    flash[:success] = "Category deleted successfully"
    redirect_to [:admin_categories]
  end

 

  private
    def cat_params
       params.require(:categorie).permit(:name)
    end
 

end

app/views/admin/categories/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@category.name}" %></h3>
</div>
<%= render "form" %>

app/views/admin/categories/_index.html.erb
<% @allcategory.each do |category| %>
  <tr>
    <td style="width:80%;"><%= category.name.html_safe %></td>
    <td><%= link_to "Edit", edit_admin_category_path(category), remote: true, class: "btn btn-warning" %></td>
    <td><%= link_to "Delete", [:admin, category], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
  </tr>
<% end %>

app/views/admin/categories/_new.html.erb
<div class="modal-header">
<h3>New Category</h3>
</div>
<%= render "form" %>

app/views/admin/categories/_save.js.erb
$("ul.errors").html("")
<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
   
  //$(".product-index").html("<%= escape_javascript(render 'index') %>")
  window.location = "/admin";
  //$("#product-modal").modal("hide")
<% end %>

app/views/admin/categories/_savenew.js.erb
$("ul.errors").html("")
<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".product-index").html("<%= escape_javascript(render 'index') %>")
  //window.location.reload();
  $("#product-modal").modal("hide")
<% end %>

app/views/admin/categories/create.js.erb
<%= render "save" %>

app/views/admin/categories/edit.html.erb
<h1>Update Category</h1> 
 <%= form_for([:admin, @category]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :name %></td>
		     <td> <%= c.text_field :name %></td>
		</tr>
		
	    <tr>
	     	<td> <%= c.submit "Update new category", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_categories_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/categories/edit.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/admin/categories/index.html.erb
<div class="container">
<div class="page-header">
<h1 class="category">Category List</h1>
<%= link_to 'Dashboard(Home)', admin_path, class: "btn btn-info category-bttn" %>
<%= link_to 'Add New Category', new_admin_category_path, remote: true, class: "btn btn-info category-bttn" %>
</div>

<% if @allcategory.count == 0 %>
<%= "No record presents" %>
<% else %>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr class="active">
    <th >Name</th>
    <th></th>
    <th></th>
    </tr>
    <tbody class="product-index">
      <%= render "index" %>
    </tbody>
  </thead>  
  </table>
</div>
	
<% end %>	
 <br><br>
 <%# = will_paginate @allcategory %>	
 <%= will_paginate @allcategory, renderer: BootstrapPagination::Rails %>
 </div>
 
 
 

<div id="product-modal" class="modal fade">
<div class="modal-dialog">
    <div id="inner-product-modal" class="modal-content"></div>
</div>
</div>

app/views/admin/categories/index.js.erb
$('.product-index').html("<%= escape_javascript(render("index"))%>")

app/views/admin/categories/new.html.erb
<h1>Add New Category</h1> 
 <%= form_for([:admin, @category]) do |c| %>
<table>
   
    	<%= render 'shared/error_messages' ,object: c.object %>
		<tr>
		     <td> <%= c.label :name %></td>
		     <td> <%= c.text_field :name %></td>
		</tr>
		
	    <tr>
	     	<td> <%= c.submit "Create new category", class: "btn btn-large btn-primary" %></td>
	     	<td><%= link_to 'Cancel', admin_categories_path, class: "btn btn-info" %></td>
	    </tr>
    
</table>  
<% end %>

app/views/admin/categories/new.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/admin/categories/show.html.erb
<h1>Show Categories</h1> <br><br>

<table border=0 cellspaceing="5">
	<tr>
		<td>Name</td><td>:</td><td><%= @category.name %></td>
	</tr>	
	
</table>	

<br>
<%= link_to 'Back', admin_categories_path, class: "btn btn-info" %>
<br>

app/views/admin/categories/update.js.erb
<%= render "save" %>