config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    get '', to: 'categories#index', as: '/'
    resources :dashboard
    resources :categories 
    resources :pages
    resources :userlogs do
      collection do
        get :mostactivepage
        get :mostactiveuser
        get :userpagecount
        get :userlist
      end
    end
  end

  devise_for :users, controllers: { invitations: 'devise/invitations' },:skip => [:registrations] 

  resources :dashboard
  resources :pages
  resources :userlogs
  root 'dashboard#home'
  get 'home' => 'dashboard#home'
  get 'about' => 'dashboard#about'
  get 'contact' => 'dashboard#contact'
  get 'users/sign_up' => 'dashboard#signup'
  post '/ajax/sum3' => 'pages#ajax_sum3'
   
  
 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #:registerable,
  devise :invitable, :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:username]
  #:confirmable
  #attr_accessible :username

  validates :username, presence:   true,
             uniqueness: { case_sensitive: false }

  belongs_to :role
  has_many :userlogs

  

end

app/controllers/admin/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

  before_filter :configure_permitted_parameters, if: :devise_controller?	

     
  private

  # this is called when creating invitation
  # should return an instance of resource class
  def invite_resource
    ## skip sending emails on invite
    resource_class.invite!(invite_params, current_inviter) do |u|
      #u.skip_invitation = true
       u.skip_invitation = false
    end
  end

  # this is called when accepting invitation
  # should return an instance of resource class
  def accept_resource
    resource = resource_class.accept_invitation!(update_resource_params)
    ## Report accepting invitation to analytics
    Analytics.report('invite.accept', resource.id)
    resource
  end

  def configure_permitted_parameters
	  # Only add some parameters
	  devise_parameter_sanitizer.for(:accept_invitation).concat [:email, :username]
	  # Override accepted parameters
	  devise_parameter_sanitizer.for(:accept_invitation) do |u|
    u.permit(:email, :username,:password, :password_confirmation,:invitation_token)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
  	@user = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      flash[:success] = "User is added successfully!"
      redirect_to [:admin, @user]
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User is updated successfully!"
      redirect_to [:admin_user]
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted successfully"
    redirect_to [:admin_categories]
  end

  private
    def user_params
       params.require(:user).permit(:first_name,:last_name,:email,:phone,:state)
    end
 

end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def new
  	super
  end

  def edit
    super
  end

  def create
    super
    flash[:notice] = "User invited" #need to check if create was successful
  end

  private

  # this is called when accepting invitation
  # should return an instance of resource class
  def accept_resource
    resource = resource_class.accept_invitation!(update_resource_params)
    resource.role = Role.find_by(name: "registered") #needs to change to "registered" once that section is ready
    resource
  end

  def configure_permitted_parameters
  	  devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username,:email, :password, :password_confirmation)
   		 end

	  # Override accepted parameters
	  devise_parameter_sanitizer.for(:accept_invitation) do |u|
	    u.permit(:username,:password, :password_confirmation, :invitation_token)
    end
  end

end

app/views/users/invitations/edit.html.erb
<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put ,class:"form-signin form-invitation"} do |f| %>
<h3><%= t 'devise.invitations.edit.header' %></h3>

  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

 
  <%= f.text_field :username , class: "form-control", :autofocus => true , :placeholder=>"Username" %>

  <%= f.password_field :password , class: "form-control",  :placeholder=>"Password" %>
   
  <%= f.password_field :password_confirmation , class: "form-control",  :placeholder=>"Password Confirmation" %>

  <p><%= f.submit t("devise.invitations.edit.submit_button") , class: "btn btn-lg btn-login btn-block" %></p>
<% end %>

app/views/users/invitations/new.html.erb


<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post,class:"form-signin form-invitation"} do |f| %>
<h3><%= t "devise.invitations.new.header" %><%= %></h3>

  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  
  <%= f.text_field field, class: "form-control", :autofocus => true , :placeholder=>"Email"%></p>
  
<% end -%>

 <%= f.submit t("devise.invitations.new.submit_button") , class: "btn btn-lg btn-login btn-block" %> <%= link_to "Cancel", admin_path , class: "btn btn-lg btn-login btn-block" %>
<% end %>
